FROM hexpm/elixir:1.9.4-erlang-22.3.4.2-debian-buster-20200511 AS dev

ARG DOCKER_HOST_USER_NAME=ebnis

ARG APP_DEPS="openssl git ca-certificates"
ARG HOME_VAR=/home/${DOCKER_HOST_USER_NAME}
ARG APP_PATH=${HOME_VAR}/src

RUN apt-get update \
  && apt-get install -y ${APP_DEPS} ${BUILD_DEPS} --no-install-recommends \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /usr/share/doc && rm -rf /usr/share/man \
  && apt-get clean \
  && groupadd ${DOCKER_HOST_USER_NAME} \
  && useradd -m -g ${DOCKER_HOST_USER_NAME} ${DOCKER_HOST_USER_NAME}

COPY ./docker/entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR ${APP_PATH}

COPY mix.exs mix.lock ./
COPY config config
COPY . .

RUN chown -R \
  ${DOCKER_HOST_USER_NAME}:${DOCKER_HOST_USER_NAME} \
  ${HOME_VAR} \
  && rm -rf docker

# run app as non root user to avoid volume mount problems
USER ${DOCKER_HOST_USER_NAME}

# hex has to be installed as the user that will compile and run our app
RUN mix local.hex --force \
  && mix local.rebar --force \
  && mix do deps.get, deps.compile

CMD ["/bin/bash"]
