version: "3.4"
services:
  db:
    volumes:
      - ./docker/data/postgres_dev:/var/lib/postgresql/data

  api:
    build:
      dockerfile: Dockerfile.dev
      args:
        EBNIS_DOCKER_HOST_USER_NAME: "${EBNIS_DOCKER_HOST_USER_NAME}"
    image: ebnis-dev
    entrypoint: ["/home/${EBNIS_DOCKER_HOST_USER_NAME}/app/entrypoint.sh"]
    user: "${EBNIS_DOCKER_HOST_USER_NAME}"
    volumes:
      - ./apps:/app/apps
      - ./config:/app/config
      - ./deps:/app/deps
      - ./.iex.exs:/app/.iex.exs
      - ./mix.exs:/app/mix.exs
      - ./mix.lock:/app/mix.lock
