FROM elixir:1.9.4-slim AS dev

ARG APP_DEPS="openssl git"
ARG MIX_ENV=dev
ARG EBNIS_DOCKER_HOST_USER_NAME
ARG HOME_VAR=/home/${EBNIS_DOCKER_HOST_USER_NAME}
ARG APP_PATH=${HOME_VAR}/app
ARG APPS_PATHS=${APP_PATH}/apps

ENV MIX_ENV=${MIX_ENV}

# The EBNIS_DATABASE_HOST must be the same as the postgres service name in
# docker-compose.yml
ENV EBNIS_DATABASE_HOST=db

RUN apt-get update \
  && apt-get install -y ${APP_DEPS} --no-install-recommends \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /usr/share/doc && rm -rf /usr/share/man \
  && apt-get clean

RUN groupadd ${EBNIS_DOCKER_HOST_USER_NAME} && \
  useradd -m -g ${EBNIS_DOCKER_HOST_USER_NAME} \
  ${EBNIS_DOCKER_HOST_USER_NAME}

USER ${EBNIS_DOCKER_HOST_USER_NAME}

RUN mix local.hex --force \
  && mix local.rebar --force

USER root

RUN mkdir -p ${APPS_PATHS}
WORKDIR ${APP_PATH}

COPY mix.exs mix.lock ./
COPY config config

# copy mix.exs files from apps/
WORKDIR ${APPS_PATHS}

RUN mkdir -p ${APPS_PATHS}/ebnis
COPY apps/ebnis/mix.exs                         ebnis

RUN mkdir -p ${APPS_PATHS}/ebnis_emails
COPY apps/ebnis_emails/mix.exs                  ebnis_emails

RUN mkdir -p ${APPS_PATHS}/ebnis_data
COPY apps/ebnis_data/mix.exs                    ebnis_data

RUN mkdir -p ${APPS_PATHS}/ebnis_web
COPY apps/ebnis_web/mix.exs                     ebnis_web

WORKDIR ${APP_PATH}
COPY ./docker/entrypoint.sh .
COPY . .
RUN rm -rf ./docker ./rel

RUN chown -R ${EBNIS_DOCKER_HOST_USER_NAME}:${EBNIS_DOCKER_HOST_USER_NAME} \
  ${HOME_VAR}

USER ${EBNIS_DOCKER_HOST_USER_NAME}

RUN GIT_SSL_NO_VERIFY=1 mix do deps.get, compile

EXPOSE ${EBNIS_PORT}

RUN chmod +x entrypoint.sh

CMD ["/bin/bash"]
