use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

# config to use in releases
config :ebnis_web, EbnisWeb.Endpoint,
  url: [
    host: "localhost"
  ],
  server: true

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :ebnis_web, EbnisWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         :inet6,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :ebnis_web, EbnisWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# Do not print debug messages in production
config :logger, level: :info

config :bcrypt_elixir, :log_rounds, 12

######################################################################

# in releases, the below should be removed

config :ebnis_data, EbnisData.Repo,
  ssl: true,
  url: System.get_env("DATABASE_URL"),
  pool_size:
    "EBNIS_POOL_SIZE"
    |> System.get_env()
    |> Kernel.||("18")
    |> String.to_integer()

secret_key = System.get_env("SECRET_KEY_BASE")

port =
  System.get_env("PORT")
  |> Kernel.||(raise "environment variable PORT is missing")
  |> String.to_integer()

config :ebnis_web, EbnisWeb.Endpoint,
  http: [:inet6, port: port],
  url: [
    scheme: "https",
    host: "ebnis.herokuapp.com",
    port: port
  ],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  secret_key_base: secret_key,
  check_origin: [
    "//ebnis.netlify.com"
  ]
