export const CLOSE_NOTIFICATION_TIMEOUT_MS = 10 * 1000;
export const FETCH_EXPERIENCES_MAX_TIMEOUT = 5000;

export const FETCH_EXPERIENCES_TIMEOUTS = [
  2000,
  3000,
  FETCH_EXPERIENCES_MAX_TIMEOUT,
];

export const MAX_TIMEOUT_MS = 10 * 1000;
